### ISSUE TITLE
Http\Request::isPost should return true for post requests

### ISSUE THREAD

**Issue by tflori** [FloKnapp/Faulancer#1]
http://stackoverflow.com/questions/409351/post-vs-serverrequest-method-post

A post request does not necessarily have `$_POST` filled.

The same issue is valid for `Http\Request::isGet`

**Comment by FloKnapp** [comment]
Thank you for reporting! Was fixed in commit https://github.com/FloKnapp/faulancer/commit/8e44c197cec510462dc1810b33df9dd2a1b9f528
